### PR TITLE
Added inverted drawing mode (shift key)

### PR DESCRIPTION
**Pull request by Dzeri96**
_Let me just preface this by saying that my changes were written very hastily because I'm under time pressure. I expect that this will be refactored somewhat. I also haven't tested everything thoroughly, though apart from one bug, everything seems to work._

What this PR brings is the possibility to make the plugin's default behavior be drawing, and holding shift would make the canvas movable. I also wanted to make the existing annotations selectable in both modes, but still allow new ones to be drawn inside old ones. When one annotation is selected however, the drawing mode is disabled until it is explicitly unselected.

**Things I added/changed:**
- `invertDrawingMode` prop in `AnnotationLayer` which dictates the behavior.
- `lastMouseDown` is now "global" inside `AnnotationLayer`, allowing it to be changed from different drawing tools.
- `setInvertDrawingMode(enable: boolean)` function which allows to programmatically set the `invertDrawingMode` prop.
- The MODE button in `index.html` now toggles this new prop instead being a one-shot button. This made more sense to me and was useful for testing.
- Changed the comments accordingly

**TODO:**
- Add the prop and function to the appropriate documentation pages.

**Bugs:**
- I was getting something similar to `this.selectedShape is undefined` on `OSDAnnotationLayer.js:591`. I couldn't reliably reproduce it, but I'm sure it's a side-effect, both literally and one of my limited knowledge of the codebase.

I'm using this plugin in my master's thesis which is why I'm under time pressure. I'd appreciate it if this could get reviewed and perhaps published in a pre-release version so that I can reference it in my code without having to change a bunch of information in the package and publishing it to npm.

### CODE REVIEW

**Comment by rsimon** [comment]
Thanks - I'll need to take a closer look! (But will probably get around to it on the weekend at the earliest.)

Just a heads-up: I was thinking about changing a way this works more globally. There is currently an API method [setDrawingEnabled](https://recogito.github.io/annotorious/api-docs/osd-plugin/#setdrawingenabled) which allows you to control drawing- vs. navigation-mode programmatically. This works in addition to the SHIFT key.

To make things more generic, I was actually thinking of allowing people to define a keycode for the shortkey (SHIFT as default), or `null` to disable the shortkey altogether. With the shortkey disabled, it would be up to the application to implement their own behavior - including an inversed behavior like the one you describe. I wonder which approach is more generic, and/or has simpler API design.

I'll also check out that bug you reported!

Thx,
R

P.S.: ah - great to see you're at the TU Wien. It's been a while for me ;-) Can I ask what you are working on in your Master's thesis?

**Comment by Dzeri96** [comment]
Speaking for myself, the most intuitive implementation would be to have two functions/props. The first one would be called `setDrawingMode`, and would accept an enum with three values: 
- `pushToDraw` - Like it is now.
- `invertedPushToDraw` - What I implemented.
- `programmatic` - What you suggested, the plugin wouldn't switch modes automatically, though we have to consider if we still want to block drawing when an annotation is selected. I think it would make sense.

Another function, let's call it `drawingMetaKey`, would take the keycode which would override shift as the default drawing mode activator.

My master's thesis is on the automatic extraction of figures, tables and captions from scientific publications. We initially wanted to implement a new hybrid approach that combines hand-crafted rules and a CNN, but the focus shifted towards building a general validation dataset annotated by humans. I'm using annotorious in the annotation client that will be utilized by people on Amazon's Mechanical Turk platform. Since I got funding trough a research project (similar to this tool), I'm looking to utilize every cent as well as I can, which means saving the annotators time by having drawing mode be enabled by default 😅.
If you want more info we can get in contact. I'm definitely gonna credit you in my work and I know this collaboration is gonna make a great slide in the final presentation. Funnily enough, I was very close to applying for a job at the AIT. Maybe one day though...

**Comment by Dzeri96** [comment]
Quick update: I fixed the bug I mentioned earlier. Since I added the setting of `lastMouseDown` even in draw mode, `onClick` would mistake it for a real click if someone were to draw an annotation under 250ms. Now I'm setting a sort of a cookie when releasing the drawing tool and consuming it in the following `onClick` call, which clears any future clicks.
This reliably works because of the event order in the DOM.

I think the solution is quite elegant for what it is... something slapped on to avoid breaking anything else.

**Comment by rsimon** [comment]
Finally getting around to looking into this for real... Ok, I was leaning toward removing the hotkey from the core altogether, and leaving this up to a plugin. But arguably the plugin would be so small it probably wouldn't be worth the hassle. I'll try to do a final review and merge over the next days. But will probably make minor changes on the API end. 

My idea would be a single init property, e.g. `hotkey` which could either take a keycode as a value (__Shift__ by default), or an object { code: [keycode], inverted: [Boolean] }.

Is there a particular reason you need to change the inverted behavior dynamically?

**Comment by Dzeri96** [comment]
> Is there a particular reason you need to change the inverted behavior dynamically?

I'm not using it currently, but I could see an app implementing some kind of settings page where this could be toggled.

**Pull request merged**
